### Register
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "szymon@gmail.com",
    "password": "12345",
    "userAvatar": "somephoto",
    "phoneNumber": "88271722",
    "firstname": "Tomasz",
    "lastname": "Jaskółka",
    "isActive": false

}

### Login
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "szymon@gmail.com",
    "password": ""
}

### Who am i
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout/8


### Get all users
GET http://localhost:3000/auth/allUsers

### Get user
GET http://localhost:3000/auth/5


### Delete user
DELETE http://localhost:3000/auth/3

### Update an user
PATCH http://localhost:3000/auth/8
Content-type: application/json

{
    "email": "szymon@gmail.com",
    "password": "12345"
}